version: '3.6'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:2.5
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls
      - --providers.file.directory=/dyn/
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ./dyn:/dyn
    tty: true

  minio: # credentials -> minioadmin:minioadmin
    image: minio/minio:latest
    command: server /data --console-address :80
    user: 1000:1000
    labels:
      traefik.http.routers.minio.rule: Host(`minio.localhost`)
      traefik.http.services.minio.loadbalancer.server.port: 80
    volumes:
      - ./volumes/minio:/data
