version: '3.6'

services:
  traefik:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
  whoami:
    image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    labels:
      traefik.tcp.routers.whoami.rule: HostSNI(`*`)
      traefik.tcp.routers.whoami.middlewares: test-inflightconn
      traefik.tcp.middlewares.test-inflightconn.inflightconn.amount: 1
