version: '3.9'

services:
  traefik:
    image: traefik/traefik:latest
    # image: traefik:v2.7
    command:
      - --api.insecure=true
      - --providers.docker
      # - --providers.file.directory=/dyn
      - --log.level=DEBUG
      - --metrics.openTelemetry.address=http://otel-collector:4318/v1/metrics
      - --tracing.openTelemetry.endpoint=otel-collector:4318
      - --tracing.openTelemetry.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dyn:/dyn
    tty: true

  whoami:
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.services.whoami.loadbalancer.server.port: 80

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: --config=/collector-config.yml
    volumes:
      - ./collector-config.yml:/collector-config.yml
    ports:
      - "4317-4319:4317-4319"
