version: '3.6'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:2.4.8
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-d.yml:/configurations/dynamic.yml:ro
      - ./traefik.yml:/traefik.yml:ro

  portainer:
    image: portainer/portainer-ce:alpine
    # hostname: portainer
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    labels:
      # - "traefik.enable=true"

      # Access Router
      # - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.middlewares=portainer-ip"
      - "traefik.http.routers.portainer.service=portainer-service"

      # Ip Whitelist
      - "traefik.http.middlewares.portainer-ip.ipwhitelist.sourcerange=192.168.64.1/32"
      # - "traefik.http.middlewares.portainer-ip.ipwhitelist.sourcerange=127.0.0.1/32"

      # Service
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
