api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

pilot:
  token: ""

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

  matrix:
    address: :8448
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker: true
    # network: traefik-public
    # swarmMode: true
    # endpoint: "unix:///var/run/docker.sock"
    # exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email:
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
