version: '3.9'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:v2.7
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --providers.file.directory=/dyn
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./file.toml:/dyn/file.toml
    tty: true

  whoami:
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.middlewares: disable-cors@file
      # traefik.http.middlewares.cors.headers.accesscontrolallowmethods: POST,GET,OPTIONS,PUT,PATCH,DELETE
