[http.middlewares]
  [http.middlewares.disable-cors.headers.customResponseHeaders]
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 600
    Access-Control-Allow-Methods = ["POST", "GET", "OPTIONS", "PUT","PATCH","DELETE"]
    Access-Control-Allow-Headers = ["*"]
