version: '3.9'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      - traefik.http.routers.pca_gql.tls=true
      - traefik.http.routers.pca_gql.tls.certresolver=leacme
      - traefik.http.routers.pca_gql.rule=Host(`pca.cdaringe.com`)
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolallowmethods=GET,OPTIONS
      # - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolalloworigin=https://cdaringe.static.observableusercontent.com
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolalloworiginlist=https://cdaringe.static.observableusercontent.com
      - traefik.http.middlewares.pca_gql_headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.pca_gql_headers.headers.addvaryheader=true
      - traefik.http.routers.pca_gql.middlewares=pca_gql_headers@docker
