# [http.routers.api-dashboard]
  # rule = "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
  # service = "api@internal"

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/certs/certificate.crt"
    keyFile = "/etc/traefik/certs/certificate.key"
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/certs/certificate.crt"
        keyFile  = "/etc/traefik/certs/certificate.key"
