version: "3.3"

services:

  traefik:
    # image: traefik:v2.3.4
    image: traefik:v2.5
    tty: true
    ports:
      - "8080:8080"
      - "9100:9100"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"

  minio1:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    container_name: "minio1"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    volumes:
      - data1-1:/data1
      - data1-2:/data2
      - ./minio-certs:/root/.minio
    command: server https://minio{1...2}/data{1...2}

  minio2:
    image: minio/minio:RELEASE.2020-12-03T05-49-24Z
    container_name: "minio2"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    volumes:
      - data2-1:/data1
      - data2-2:/data2
      - ./minio-certs:/root/.minio
    command: server https://minio{1...2}/data{1...2}

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
