version: '3.6'

services:
  traefik:
    image: traefik:2.5
    command:
      - '--providers.docker'
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.sub-hoami-localhost.rule=Host(`sub.whoami.localhost`)"
      - "traefik.http.routers.whoami-localhost.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.rule=Host(`whoami`)"
