version: "3.3"
services:
  traefik:
    image: traefik:2.5
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.websecure.address=:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  badrequest:
    build: .
    image: traefik/whoami
    labels:
      traefik.enable: true
      # traefik.http.services.test.loadbalancer.server.port: 8090
      traefik.http.services.test.loadbalancer.server.port: 80
      traefik.http.routers.test.rule: Host(`badrequest.localhost`)
      traefik.http.routers.test.tls: true
    ports:
      - "8090:80"
      # - "8090:8090"
