---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik

spec:
  selector:
    matchLabels:
      app: traefik

  template:
    metadata:
      labels:
        app: traefik

    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          # image: traefik:v2.5
          image: traefik/traefik:experimental-v2.5
          imagePullPolicy: Never
          args:
            - --api.insecure
            - --api.debug
            - --providers.kubernetesIngress
            - --metrics.prometheus
          ports:
            - containerPort: 80
              name: http

            - containerPort: 8080
              name: admin

---
apiVersion: v1
kind: Service
metadata:
  name : traefik

spec:
  type: LoadBalancer
  selector:
    app: traefik

  ports:
    - port: 80
      name: http
      targetPort: http

    - port: 8080
      name: admin
      targetPort: admin
