---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoamitcp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoamitcp

  template:
    metadata:
      labels:
        app: whoamitcp

    spec:
      containers:
        - name: whoamitcp
          image: traefik/whoamitcp

---
apiVersion: v1
kind: Service
metadata:
  name: whoamitcp

spec:
  selector:
    app: whoamitcp

  ports:
    - protocol: TCP
      port: 8080
