apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik-lb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-lb
  template:
    metadata:
       labels:
          app: traefik-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          tty: true
          image: traefik:v2.5
          #          image: traefik/traefik:latest
          imagePullPolicy: IfNotPresent
          args:
            - --log.level=DEBUG
            - --api.insecure
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls.certresolver=myresolver
            - --certificatesresolvers.myresolver.acme.email=tom@traefik.io
            # - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
            - --certificatesresolvers.myresolver.acme.tlschallenge=true
            - --certificatesresolvers.myresolver.acme.storage=/acme/acme.json
            # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: api
              containerPort: 8080

          volumeMounts:
            - mountPath: /acme/
              name: traefik-acme-configmap

      volumes:
        - name: traefik-acme-configmap
          secret:
            secretName: traefik-acme-configmap
            items:
              - key: acme.json
                path: acme.json
                mode: 0600

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-acme-configmap
data:
  acme.json: |

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 443
      targetPort: 443
      name: websecure
  type: LoadBalancer
