version: '3.6'

services:
  traefik:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
    ports:
      - "81:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    labels:
      traefik.http.middlewares.login-ratelimit.ratelimit.average: 100
      traefik.http.middlewares.login-ratelimit.ratelimit.burst: 10
      traefik.http.routers.login-whoami.rule: Host(`whoami.localhost`) && PathPrefix(`/api/login`)
      traefik.http.routers.login-whoami.middlewares: login-ratelimit

      traefik.http.middlewares.api-ratelimit.ratelimit.average: 500
      traefik.http.middlewares.api-ratelimit.ratelimit.burst: 50
      traefik.http.routers.api-whoami.rule: Host(`whoami.localhost`) && PathPrefix(`/api`)
      traefik.http.routers.api-whoami.middlewares: api-ratelimit
