version: '3.6'

services:
  traefik:
    # image compiled from https://github.com/traefik/traefik/pull/8592
    # image: traefik/traefik:latest
    image: traefik:2.5
    command:
      - '--api.insecure=true'
      - '--log.level=DEBUG'
      - '--providers.consulcatalog.endpoint.address=consul:8500'
      - '--providers.consulcatalog=true'
      - '--providers.consulcatalog.namespace=test-namespace'
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - consul

  consul:
    image: hashicorp/consul-enterprise
    ports:
      - 8500:8500
    command: agent -server -bootstrap -ui -client 0.0.0.0 -hcl 'connect { enabled = true }' -grpc-port 8502 -config-dir /json
    environment:
      CONSUL_LICENSE: 02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJ5CEE22NKRLGYWSXJF2E6V2KNBGVGMBQJZCFE3CMKRIXUTSXIV2E2RCBPJHUIWJRJZ5GI22OGJEXOSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJF4VU3K2NNHVOTJTLJJTC3CZKRHGUTCUNRVU4RCRORNGUUTJLJUTANCNPJRTCTT2IZVU6VCFPBNGURLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SFORGVIRLUJVVGYVKNKRATMTL2JU3E2RCFOVHHUWJTJVKEKNCOKRKTCV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPBGFIRLYJRKESNKWIRCXOT3KJV5E62SBPBLWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKIV2E2VCJORGWU3CVJVKECNSNPJGTMTKEIZQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJCXITKUJF2E26SCKVGVIQJWJV5E2NSNIRDGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNVHHMYTOJYYWEQ2JONEW2WTTLFLWI6SJNJYDOSLNGF3FUSCWONNFQTLJJ5WHG2K2GJ4HMWLNIZZUYWC2OBRTE3DJMFLXQ4DEJBVXIY3NHEYWIR3MOVNHSML2LEZEM422KNEXGSLNMR3GI3KWPFRG2RTVLEZFK5DDI44XGYKXJY2US3BRHFTFCPJ5FZEDKR3UJNKWIYTZK5WW243BORGU6M3HLJIDE5LCPFFTKMJPJJLHM4LJPE4HKQ3CF5EHGZZZIMYWWYSQLF2GCSJZIJEDEU2KG5RVASKQKJFEMWSOGBJEGU3INB3GMTSTMFEE4OKDIFYDCZCBNNRWCNDEKYYDGMZYKB3W2VTMMF3EUUBUOBFHQSKJHFCDMVKGJRKWCVSQNJVVOSTUMNCDM4DBNQ3G6T3GI5XEWMT2KBFUUUTNI5EFMM3FLJ3XCRTFFNXTO2ZPOMVUCVCONBIFUZ2TF5FVMWLHF5FSW3CHKB3UYN3KIJ4ESN2HJ5QWWNSVMFUWCSDPMVVTAUSUN43TERCRHU6Q
    volumes:
      - './json:/json'
      - './namespace.json:/namespace.json'

  whoami:
    image: traefik/whoami
    hostname: whoami1
