version: '3.9'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:v2.7
    command:
      - --api.insecure=true
      - --providers.docker
      # - --providers.file.directory=/dyn
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dyn:/dyn
    tty: true

  whoami:
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      # traefik.http.routers.whoami.rule: Host(`w&ho_ami.localhost`)
      traefik.http.routers.whoami.rule: Host(`who_ami.localhost`)
      traefik.http.routers.whoami.tls: ""
