version: '3.9'

services:
  traefik:
    image: traefik/traefik:latest
    # image: traefik:v2.9
    command:
      - --api.insecure=true
      - --providers.docker
      # - --providers.file.directory=/dyn
      - --log.level=DEBUG
      # - --entrypoints.web.address=:80
      # - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.http.tls=true
    ports:
      - 80:80
      # - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dyn:/dyn
    tty: true
    # environment:
      # GODEBUG: http2debug=2
      # GRPC_TRACE: all
      # GRPC_VERBOSITY: DEBUG

  python:
    image: python
    command: python -m http.server
    volumes:
      - ./vol:/vol
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.middlewares: test-compress
      traefik.http.middlewares.test-compress.compress: true
      # traefik.http.middlewares.test-compress.compress.minresponsebodybytes: 4
      traefik.http.services.whoami.loadbalancer.server.port: 8000
