apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE2MzIzMjQwNjMwHhcNMjEwOTIyMTUyMTAzWhcNMzEwOTIwMTUyMTAz
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE2MzIzMjQwNjMwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAROMtjSIvTuoc5Uo6Cd0Uuem1p2FUGipiksgrE26gvX
      88mHS43COnHU8/1iR6pZ1Qir8Vv4QWVvpOdF8RUhSsHCo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU+LLLH+pnknIh7RvOBt02
      rI/YZIcwCgYIKoZIzj0EAwIDSAAwRQIhAK4rVF2wu/KVruWLJfT6mUbTOuLKrO8O
      raRXh6bX9GzHAiA8ziI3rxH82GQFxyK9CyB10T1QTpEyW2E0G7U8lqdGWw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2021-09-22T15:21:22Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
      manager: k3s
      operation: Update
      time: "2021-09-22T15:21:22Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "433"
    uid: 8ee8e01b-8a0d-4bf4-8797-229c25cae83c
- apiVersion: v1
  data:
    pebble-config.json: |
      {"pebble":{"certificate":"/etc/pebble/temp-tls-leaf/cert.pem","externalAccountBindingRequired":false,"externalAccountMACKeys":{},"httpPort":80,"listenAddress":":8443","managementListenAddress":":8444","ocspResponderURL":"","privateKey":"/etc/pebble/temp-tls-leaf/key.pem","tlsPort":443}}
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIDSzCCAjOgAwIBAgIIOvR7X+wFgKkwDQYJKoZIhvcNAQELBQAwIDEeMBwGA1UE
      AxMVbWluaWNhIHJvb3QgY2EgM2FmNDdiMCAXDTIwMDQyNjIzMDYxNloYDzIxMjAw
      NDI3MDAwNjE2WjAgMR4wHAYDVQQDExVtaW5pY2Egcm9vdCBjYSAzYWY0N2IwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCaoISLUOImo7vm7sGUpeycouDP
      TcJj6CxfCbvBsrlAg8ERGIph9H7TuDnTVk46pOaoxByGlwvvh4qR/Dled+G8NCt5
      s0r0yemY/fx1grm1TmcJRO+A1P5kx/M9hy+kVcyLRvPOnvo8Thj/4zvaJDh+pSjt
      5oAQvOHt9hYwGkkvSsZw12cTUuCsbypQ4lapDSeAjp3pNlqFcWmCvF9Ib3URDybN
      JWhY6yQQe54D2LxYqxCfYZjKhNbaxlNTlHu0Ujy75I/AdSjK6DljAZh0OimuQNEm
      FyXWvpnfyHbV5f0mMiXIOo2FY8izSD7cyFagmr0XvymCtxeDK1+MvT2pM+rXAgMB
      AAGjgYYwgYMwDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
      BgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBR0MgecNe4RY575
      qAtIt6zAjbBqLTAfBgNVHSMEGDAWgBR0MgecNe4RY575qAtIt6zAjbBqLTANBgkq
      hkiG9w0BAQsFAAOCAQEAjtGjoXGRG7586vyT3XcJBa8y9MOsDhQGOec23h40NJCn
      SPF28bmTIaWhB+Hv8G+Mkyf9Ov3L5L/mH0VGvZUkMAnSdT4vaMYGrTvMtYGS/8ew
      lPnlSJ3oO9Kz9zfOneoPDD1OGkV0Oq3wLn9cq6jQgItEeACsXNtaogXJxYhvxiV1
      1k/gjXmG9pvFpb0A1bw6apxGftIViDKrPR2P/pG3QAuLKywQiNxZ5odf3kvKdZmJ
      hLbu119My9XiiWhNegufcRNRNEnKJ5AQsBEwLEnD4oeIZmFvYVKOPjfWRV5qczVi
      mUPjtQv88HhlgX/lBVWJ2VONlFWVoOreZz4GkAm5bA==
      -----END CERTIFICATE-----
    root-key.pem: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAmqCEi1DiJqO75u7BlKXsnKLgz03CY+gsXwm7wbK5QIPBERiK
      YfR+07g501ZOOqTmqMQchpcL74eKkfw5XnfhvDQrebNK9MnpmP38dYK5tU5nCUTv
      gNT+ZMfzPYcvpFXMi0bzzp76PE4Y/+M72iQ4fqUo7eaAELzh7fYWMBpJL0rGcNdn
      E1LgrG8qUOJWqQ0ngI6d6TZahXFpgrxfSG91EQ8mzSVoWOskEHueA9i8WKsQn2GY
      yoTW2sZTU5R7tFI8u+SPwHUoyug5YwGYdDoprkDRJhcl1r6Z38h21eX9JjIlyDqN
      hWPIs0g+3MhWoJq9F78pgrcXgytfjL09qTPq1wIDAQABAoIBAB0x7ZS4YtrU02eY
      8Of2JCS3BCdgETH35ljTZ6X87slllxB5R7eTCFdFU3W5t++OrxZyYMhwwIorV1iU
      /Of/TpnQZ90Eo0Rw0zBV1FMDqbi34vB3GZmDnby9nAmj+rTWllY9wU7j6W91d3bp
      GqXnbNtMp9uzR77hSu85JZtTezn4YzjIbHqd4+/+4xbOsla0wKXFjiCgYBy15a6a
      D92ypK/wyN0ghzyfNwIfnpqfHSUIOCogO8BClS3IV/wLci0hMIQlUkxm1MC7zsdN
      hLFy4I0bKzq5MA+F9Tv0S6MxUpB4vSGw0bQeZjfxuFCTcZ8XE0CMsByDW+nfGU5b
      Kmj75NECgYEAxP05uMVitQJh2Wi8kj5ufUIPA1OeGLdpuxXVkTm36Xsn4Jmv6NuU
      OaOqa7kNoYrpSlUjLBng6KetewxXWB3ykaftycutgXS/Cd8OoaHKmdBtado8m3tb
      shyTSG++8YLXVll4+Cn2DC6YHXJpq+OeDvFD+GTfgpa7kaWkBwswqZ0CgYEAyPKc
      CoMuzdLKl/+8pVAy2Yb8pcCd0+KC74BQDvusSGCJtDl4ophO2tbvt7pvQJ6PEBl+
      UDZdOohilWemG6wmswlAKsGn5L/I8946TF6r7l9CVBl9OAsSs2weZBNg5Ukqx5p+
      JryfDQfv+FJq3n1q3ECMzgj1KFMdG8khuJ71RgMCgYBLuXA7+BzGqmDE+38p1LgS
      jJdK1xT6OV96nJ0Zk4+AQGiG7W1y3R3wvlqfyGZWCBlACtRXeqc7qGGG4Kqe4/xA
      Q8akARj0n9VkTQvJ1HEWicnVnCAaQORx5owzl0lWe86dkg1vkGnWKv8sqrO2cOxs
      oBBZ5yUIhTsbdQpF7uZI/QKBgQCXOs7osnWE/UDvR84Hc+XxA8AcVmvxTKVR7fVS
      cWHlTpIUCrSZWZru45ehZDPaI/pzGVyQrXlYVdArtMe0R8kQMMQT6Y6bfyKTNgoV
      86HdUd+vP0eX5+15DsOIeXUQ2hHSCpkqOgZRXknhTtWTADxt6j6NyPwIDxT3FlXE
      hgz9VQKBgEVRIPV27tD97VfBy3PRLSSQqDcUS/LaUUXEv7H+l7VPWOffJKg+xcFJ
      nZ6akov9Z5vSDM7jjUStvaKQHV1QlqKGiVfdiLTFkwyC3B2IvxyAXWB/l+wckNP3
      SS3wHkUjXo/eWoK0wSC5yDooaklsXiXWNJtWwHiAsRqYFTUt4IQs
      -----END RSA PRIVATE KEY-----
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: pebble
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2021-09-22T15:21:32Z"
    labels:
      app.kubernetes.io/instance: pebble
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: pebble
      app.kubernetes.io/version: v2.3.0
      helm.sh/chart: pebble-0.2.2
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:pebble-config.json: {}
          f:root-cert.pem: {}
          f:root-key.pem: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: "2021-09-22T15:21:32Z"
    name: pebble
    namespace: default
    resourceVersion: "476"
    uid: 4863f979-92a3-4ba9-ace2-c0c7e4680318
- apiVersion: v1
  data:
    Corefile: |-
      .:8053 {
        errors
        health
        ready
        forward . /etc/resolv.conf
        cache 2
        reload
      }
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: pebble
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2021-09-22T15:21:32Z"
    labels:
      app.kubernetes.io/instance: pebble
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: pebble-coredns
      app.kubernetes.io/version: v2.3.0
      helm.sh/chart: pebble-0.2.2
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:Corefile: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: "2021-09-22T15:21:32Z"
    name: pebble-coredns
    namespace: default
    resourceVersion: "477"
    uid: b3d9d358-546f-4ef6-9997-704ac2ef5a14
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
