version: '3.9'

services:
  traefik:
    image: traefik/traefik:latest
    # image: traefik:v2.7
    command:
      # - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: csp
      traefik.http.middlewares.csp.headers.contentsecuritypolicy: >
        default-src 'none';
        base-uri 'self';
        connect-src 'self';
        font-src 'self';
        form-action 'self';
        frame-ancestors 'self';
        frame-src 'self' https://pilot.traefik.io;
        img-src 'self';
        object-src 'none';
        script-src 'self';
        script-src-elem 'self';
        style-src 'self';
        style-src-elem 'self';

  whoami:
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
