version: '3.6'

services:
  traefik:
    image: "traefik:latest"
    command:
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.redis.address=:6379"
      - "--api=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # networks:
      # default:
        # aliases:
          # - "api.docker.localhost"
          # - "minio.docker.localhost"

  # api:
    # build:
      # context: .
      # dockerfile: "./dockerfiles/Dockerfile-api"
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.api.entrypoints=web"
      # - "traefik.http.routers.api.rule=Host(`iris.docker.localhost`) && PathPrefix(`/api`)"

  minio:
    image: "minio/minio:latest"
    command: "server /data"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.rule=Host(`minio.docker.localhost`)"
    volumes:
      - "./volumes/minio:/data"
