version: '3.9'

services:

  traefik:
    # image: traefik:v2.7
    image: traefik/traefik:nomad
    command:
      - --api.insecure=true
      - --providers.nomad.endpoint.address=http://nomad:4646
      # - --providers.docker
      # - --providers.file.directory=/dyn
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dyn:/dyn
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.services.whoami.loadbalancer.server.port: 80

  nomad:
    image: multani/nomad:1.3.1
    command: agent -dev -log-level=DEBUG -bind=0.0.0.0
    tty: true
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hcl/jobs:/etc/nomad
      - /tmp:/tmp
