version: '3.6'

services:
  traefik:
    # image: traefik/traefik:latest
    image: traefik:2.4
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--log.level=DEBUG'
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # image: traefik/whoamitcp
    image: traefik/whoami
    labels:
      - "traefik.http.routers.secure.rule=Host(`secured.whoami.docker.localhost`)"
      - "traefik.http.routers.secure.tls=true"
      # - "traefik.http.routers.secure.middlewares=basic_auth@docker"
      # - "traefik.http.middlewares.basic_auth.basicauth.users=${USERS}"

      - "traefik.http.routers.not-secured.rule=Host(`whoami.docker.localhost`)"
  app:
    image: "tommoulard/app"
    build: .
    ports:
      - "8000:8080"
    labels:
      - "traefik.http.routers.tls-app.rule=Host(`tls.app.localhost`)"
      - "traefik.http.routers.tls-app.tls=true"

      - "traefik.http.routers.auth-app.rule=Host(`auth.app.localhost`)"
      - "traefik.http.routers.auth-app.middlewares=basic_auth@docker"
      - "traefik.http.middlewares.basic_auth.basicauth.users=${USERS}"

      - "traefik.http.routers.raw-app.rule=Host(`app.localhost`)"
