---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: whoami
      targetPort: 80
      protocol: TCP
  selector:
    app: whoami

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-external
spec:
  controller: traefik.io/ingress-controller

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-fake
spec:
  controller: traefik.io/ingress-controller

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: traefik-fake-ingress

spec:
  ingressClassName: traefik-fake
  rules:
    - host: fake.whoami.localhost
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: whoami
                port:
                  number: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: traefik-external-ingress

spec:
  ingressClassName: traefik-external
  rules:
    - host: whoami.localhost
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: whoami
                port:
                  number: 80
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
  # name: whoami
  # # namespace: test
  # annotations:
# #    kubernetes.io/ingress.class: traefik # can't set if ingressClassName is set
# spec:
  # ingressClassName: traefik-external
  # rules:
  # - host: external.localhost
  # # - host: test.mydomain.com

# ---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
  # annotations:
    # ingressclass.kubernetes.io/is-default-class: "false"
  # name: traefik-external
  # spec:
    # controller: traefik.io/ingress-controller

# ---
# kind: Ingress
# apiVersion: extensions/v1
# metadata:
  # name: extensionsv1beta1

# spec:
  # ingressClassName: traefik-external
  # rules:
    # - host: whoami
      # http:
        # paths:
          # - path: /extv1beta1
            # pathType: Prefix
            # backend:
              # serviceName: whoami
              # servicePort: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
  # name: networkingv1beta1
# spec:
  # controller: traefik.io/ingress-controller

# ---
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
  # name: traefik-internal

# spec:
  # ingressClassName: traefik-internal
  # rules:
    # - host: whoami
      # http:
        # paths:
          # - path: /internal
            # backend:
              # serviceName: whoami
              # servicePort: 80

