http:
  routers:
    Router0:
      entryPoints:
      - http
      service: wrr1
      rule: PathPrefix(`/`)

  services:
    wrr1:
      weighted:
        # failoverService: whoami2@file
        services:
          - name: whoami1@file
            weight: 1
          - name: whoami2
            weight: 10

    whoami1:
      loadBalancer:
        # failoverService: whoami2@file
        healthCheck:
          path: /health
          interval: 10s
          timeout: 3s
        servers:
          - url: http://whoami-lb1:80
          - url: http://whoami-lb2:80

    whoami2:
      loadBalancer:
        servers:
          - url: http://whoami-lb3:80
          - url: http://whoami-lb4:80

    mirrored-api:
      mirroring:
        healthCheck: {}
        service: whoami1@file
        mirrors:
        - name: whoami2@file
          percent: 10
