version: '3.9'

services:
  traefik:
    image: traefik/traefik:latest
    # image: traefik:v2.7.1
    command:
      - --api.insecure=true
      - --providers.docker
      # - --providers.file.directory=/dyn
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./dyn:/dyn
    tty: true
    labels:
      traefik.http.middlewares.rd.redirectscheme.scheme: https
      traefik.http.middlewares.rd.redirectscheme.port: 443

    # environment:
      # GODEBUG: http2debug=2
      # GRPC_TRACE: all
      # GRPC_VERBOSITY: DEBUG

  whoami:
    # image: traefik/whoamitcp # https://github.com/traefik/whoamitcp
    # image: traefik/whoamiudp # https://github.com/traefik/whoamiudp
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.middlewares: rd
      traefik.http.services.whoami.loadbalancer.server.port: 80
